### ISSUE TITLE
Help it's too powerful

### ISSUE THREAD

**Issue by Strikeless** [NikV2/BruteForceInterpolation#12]
Hello. I have not had problems with this amazing product of yours, however I believe it may be too powerful for us peasants to handle, as I seem to have broken the fourth wall of reality and now everything is gone. Please help. I miss my family.

**Comment by Strikeless** [comment]
I believe my house had met the recommended requirements for the product and I also had purchased the Verus anticheat solution thus I do not believe this is an incompatibility issue.

**Comment by NikV2** [comment]
Please open a ticket on our discord at Verus Operations LLD.

**Comment by Strikeless** [comment]
verus
