### ISSUE TITLE
Issues page not managed

### ISSUE THREAD

**Issue by JosiahWI** [NikV2/BruteForceInterpolation#15512]
The number unhelpful issues from @Gowixx is getting far out of hand. These should be cleaned up with a script.

**Comment by NikV2** [comment]
15k Issues..

Looks legit to me, I think we should go into each of them and help him.

**Comment by Alexiscomete** [comment]
We might use an action : https://github.com/NikV2/BruteForceInterpolation/actions

**Comment by DortDev** [comment]
> 15k Issues..
> 
> Looks legit to me, I think we should go into each of them and help him.

LOOL
