### ISSUE TITLE
BruteForceInterpolationException is too simple

### ISSUE THREAD

**Issue by Eoghanmc22** [NikV2/BruteForceInterpolation#16328]
BruteForceInterpolationException isnt complicated enough. It should be the longest file in the project.

**Comment by Alexiscomete** [comment]
I think we can interpolate in that file

**Comment by NikV2** [comment]
Should be fixed.

**Comment by Alexiscomete** [comment]
We can move the main class in that file with a sub class

**Comment by Eoghanmc22** [comment]
this issue has been solved
