### ISSUE TITLE
I NEED HELP

### ISSUE THREAD

**Issue by Gowixx** [NikV2/BruteForceInterpolation#21]
it only boosted my fps -150 FPS, how to boost mroe

**Comment by Alexiscomete** [comment]
close unnecessary programs and reduce graphics

**Comment by NikV2** [comment]
Alternatively you can brute force interpolate your entire computer.

**Comment by Gowixx** [comment]
How to brute force interpolate my entire computer

**Comment by Alexiscomete** [comment]
👌good work
